name: Auto Merge Security Updates Only

on:
  pull_request_target:
    types: [opened, reopened, labeled, synchronize]

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]' && contains(join(github.event.pull_request.labels.*.name, ','), 'security')
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge security updates
        uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash